### ISSUE TITLE
Blue Focuser not connecting

### ISSUE THREAD

**Issue by RomanAkhmetshyn** [ColibriKBO/ColibriObservatory#11]
When opening Focuser on Blue with the camera connected it displays Network Down. Rebooting the machine or turning off and on the camera and telescope doesn't help. Other computers don't have such a problem.
![image](https://user-images.githubusercontent.com/108425347/182655104-a0576d5a-b2e2-49b1-96cc-046f1ed96030.png)

**Comment by mjmazur** [comment]
I can see the device on the network (IP: 10.0.20.63) but it doesn't connect. I'm not sure why, but am investigating.

**Comment by mjmazur** [comment]
For some reason, the firewall was set to block inbound Seletek (focuser) connections. I've removed the two rules that were blocking it and it works now. If a pop-up window comes up in the future asking whether you want to allow access for Seletek, accept it for all networks.
