### ISSUE TITLE
2022-08-06 Field index: 999

### ISSUE THREAD

**Issue by RomanAkhmetshyn** [ColibriKBO/ColibriObservatory#12]
ACP log from the latest observations showed that all three telescopes had Field index: 999 in the end. Does this mean telescoped failed to get to the field? This was on 08-06 for all telescopes, 7-31 on Red and Green, 08-10 on Green. As I understood from the js code 999 is the maximum number of fields.

**Comment by mjmazur** [comment]
It just means that there are no more fields in the array left to observe. It's normal behaviour. A 999 tells it to abort which should shut things down and restart the script.
________________________________
From: RomanAkhmetshyn ***@***.***>
Sent: August 10, 2022 5:09 PM
To: ColibriKBO/ColibriObservatory ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ColibriKBO/ColibriObservatory] 2022-08-06 Field index: 999 (Issue #12)


ACP log from the latest observations showed that all three telescopes had Field index: 999 in the end. Does this mean telescoped failed to get to the field? This was on 08-06 for all telescopes, 7-31 on Red and Green, 08-10 on Green. As I understood from the js code 999 is the maximum number of fields.
