### ISSUE TITLE
New pointing model for Red

### ISSUE THREAD

**Issue by RomanAkhmetshyn** [ColibriKBO/ColibriObservatory#2]
Drift is 3 binned pixels (around 7 arcseconds) per minute. @mjmazur @RomanAkhmetshyn

**Comment by mjmazur** [comment]
Either polar alignment or pointing model need to be updated.

**Comment by RomanAkhmetshyn** [comment]
> Either polar alignment or pointing model need to be updated.

I could participate in that if needed

**Comment by mjmazur** [comment]
A new pointing model has been created (Jul. 6, 2022).

To create or update a model...

1. Check ACP->Preferences->Pointing Corr. tab to be sure that the 'Enable ACP pointing corrector' checkbox is checked
2. Also check 'Current number of points in model' field
3. Click 'Reset Model' button if you want an entirely new model
4. Exit parameters window by either saving or canceling
5. 'Select the Script...' - Choose the Train Corrector.vbs script from the Documents\ACP Astronomy\Scripts\UsefulScripts directory
6. Make sure that the telescope is connected, the dome is open, and the camera is connected through Maxim DL
7. Run the script and enter the number of desired points when asked

After doing the following, the telescope will move across the sky collecting images and reducing them using astrometry.net (setup is in ACP->Preferences->PinPoint & All-Sky tab). You should see the images appear in Maxim DL and you should see the solutions scroll by in the ACP script output window.

And that's it. The solution sits in a file called Active.clb that is found in e.g. \\REDBIRD\Users\Public\Documents\ACP Config. This file can be viewed in MaxPoint by clicking the 'Observations' button in MaxPoint. This allows you to see errors amongst other things

![image](https://user-images.githubusercontent.com/6187105/177570472-f27248fb-fb65-41d7-b49c-668307393bdc.png)

If you're not happy with the results, a drift polar alignment can always be performed in person.

Easy, peasy.
