### ISSUE TITLE
Elongated stars on Green

### ISSUE THREAD

**Issue by RomanAkhmetshyn** [ColibriKBO/ColibriObservatory#9]
While doing a sensitivity check I noticed that the median combined image (9 images of 0.025sec exposure I believe) uploaded to astrometry.net had pretty long stars. If it's something to do with the pointing model, I could try to fix it myself when there will be no observations planned on Green. Could you please confirm this? @mjmazur 
![image](https://user-images.githubusercontent.com/108425347/180062990-74215b66-569c-4662-abbe-9b2cf0d89991.png)

**Comment by RomanAkhmetshyn** [comment]
I just compared the first and last image of the stacked median. It appears that the stars don't move but are elongated in single images. 
![image](https://user-images.githubusercontent.com/108425347/180241678-e3cfaa74-a89f-42a6-90c6-a9df04f03a3c.png)

**Comment by mjmazur** [comment]
Ok. So, we need to focus the next clear night. We don't have an autofocus routine, but we should be able to put something together with a bit of code. I'll think about whether we can hack ACP into doing it or whether we need to write a small python script that does it.

Mike
________________________________

**Comment by mjmazur** [comment]
Is it 9 consecutive images? If so, check later in the night. It wouldn't trail that much in a quarter of a second unless the tracking is off. What do the individual images look like? Are they trailed? If so, it's likely the focus that needs to be adjusted.

Mike
________________________________
From: RomanAkhmetshyn ***@***.***>
Sent: July 20, 2022 3:11 PM
To: ColibriKBO/ColibriObservatory ***@***.***>
Cc: Michael Mazur ***@***.***>; Mention ***@***.***>
Subject: [ColibriKBO/ColibriObservatory] New pointing model for Green (Issue #9)


While doing a sensitivity check I noticed that the median combined image (9 images of 0.025sec exposure I believe) uploaded to astrometry.net had pretty long stars. If it's something to do with the pointing model, I could try to fix it myself when there will be no observations planned on Green. Could you please confirm this? @mjmazur<https://github.com/mjmazur>
[image]<https://user-images.githubusercontent.com/108425347/180062990-74215b66-569c-4662-abbe-9b2cf0d89991.png>
